### ISSUE TITLE
ERROR From The srcds.exe

### ISSUE THREAD

**Issue by ShurikenSa** [EmanDev/css-sl#2]
Hy I Have Problem With The app after i run with the luancher it appears : 
-----------------------------------------------------------------------------------------------------------------------------------------------
srcds.exe - Entry point Not Found
The procedure entry point SteamInternal_CreateInterface could not be located in the dynamic link library d:\steamcmd\steamapps\common\counter-strike source dedicated server\bin\engine.dll

-----------------------------------------------------------------------------------------------------------------------------------------------
Anyway I Loved Your App Is So Cool And Usefull Thanks

**Comment by ShurikenSa** [comment]
could abyone help me i watched youtube videos i installed visual c++ 2019 and 2015 and 2013 and didnt worked thesame error show afetr i luanch

**Comment by EmanDev** [comment]
Sorry, I just saw this. The error is in your srcds files. Verifying the files should fix the problem by running  the same command when downloading srcds, just add "verify" with other parameters. The error is not connected to this app.
